apiVersion: {{ include "deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: horusec-manager
  name: {{ .Values.components.manager.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.components.manager.pod.autoscaling.enabled }}
  replicas: {{ .Values.components.manager.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: horusec-manager
  template:
    metadata:
      labels:
        app: horusec-manager
    spec:
      {{- include "manager.imagePullSecrets" . | nindent 6 -}}
      containers:
        - env:
          - name: REACT_APP_HORUSEC_ENDPOINT_API
            value: {{ .Values.components.api.ingress.scheme -}}:\/\/{{- .Values.components.api.ingress.host }}
          - name: REACT_APP_HORUSEC_ENDPOINT_ANALYTIC
            value: {{ .Values.components.analytic.ingress.scheme -}}:\/\/{{- .Values.components.analytic.ingress.host }}
          - name: REACT_APP_HORUSEC_ENDPOINT_ACCOUNT
            value: {{ .Values.components.core.ingress.scheme -}}:\/\/{{- .Values.components.core.ingress.host }}
          - name: REACT_APP_HORUSEC_ENDPOINT_AUTH
            value: {{ .Values.components.manager.ingress.scheme -}}:\/\/{{- .Values.components.auth.ingress.host }}
          - name: REACT_APP_HORUSEC_MANAGER_PATH
            value: \{{ .Values.components.manager.ingress.path }}
          {{- if eq .Values.components.auth.type "keycloak" }}
          {{- $parsed := urlParse (required "A valid global.keycloak.publicURL is required!" .Values.global.keycloak.publicURL) }}
          - name: REACT_APP_KEYCLOAK_BASE_PATH
            value: {{ $parsed.scheme -}}:\/\/{{- $parsed.host -}}\{{- $parsed.path }}
          - name: REACT_APP_KEYCLOAK_CLIENT_ID
            value: {{ .Values.global.keycloak.clients.public.id }}
          - name: REACT_APP_KEYCLOAK_REALM
            value: {{ .Values.global.keycloak.realm }}
          {{- end }}
          {{- if .Values.components.manager.extraEnv }}
          # Extra environment variables
          {{- toYaml .Values.components.manager.extraEnv | nindent 12 }}
          {{- end }}
          image: "{{ template "manager.image" . }}"
          imagePullPolicy: {{ .Values.components.manager.container.image.pullPolicy | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          name: horusec-manager
          ports:
          {{- range $key, $value := .Values.components.manager.port }}
            - containerPort: {{ $value }}
              name: {{ $key }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          {{- if .Values.components.manager.container.livenessProbe }}
            failureThreshold: {{ .Values.components.manager.container.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.components.manager.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.components.manager.container.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.components.manager.container.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.components.manager.container.livenessProbe.timeoutSeconds }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          {{- if .Values.components.manager.container.readinessProbe }}
            failureThreshold: {{ .Values.components.manager.container.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.components.manager.container.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.components.manager.container.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.components.manager.container.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.components.manager.container.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.components.manager.container.resources }}
          resources: {{- toYaml .Values.components.manager.container.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.components.manager.container.securityContext.enabled }}
          securityContext: {{- omit .Values.components.manager.container.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
      {{- if .Values.components.manager.pod.securityContext.enabled }}
      securityContext: {{- omit .Values.components.manager.pod.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: manager
      terminationGracePeriodSeconds: 30
