apiVersion: {{ include "deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: horusec-webhook
  name: {{ .Values.components.webhook.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.components.webhook.pod.autoscaling.enabled }}
  replicas: {{ .Values.components.webhook.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: horusec-webhook
  template:
    metadata:
      labels:
        app: horusec-webhook
    spec:
      {{- include "webhook.imagePullSecrets" . | nindent 6 -}}
      containers:
        - env:
          - name: HORUSEC_PORT
            value: {{ .Values.components.webhook.port.http | quote }}
          - name: HORUSEC_SWAGGER_HOST
            value: 0.0.0.0
          - name: HORUSEC_BROKER_HOST
            value: {{ required "A valid global.broker.host is required!" .Values.global.broker.host }}
          - name: HORUSEC_BROKER_PORT
            value: {{ .Values.global.broker.port | quote }}
          - name: HORUSEC_BROKER_USERNAME
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.broker.user.secretKeyRef | nindent 16 }}
          - name: HORUSEC_BROKER_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.broker.password.secretKeyRef | nindent 16 }}
          - name: HORUSEC_DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.database.user.secretKeyRef | nindent 16 }}
          - name: HORUSEC_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.database.password.secretKeyRef | nindent 16 }}
          - name: HORUSEC_DATABASE_SQL_URI
            value: {{ include "global.database.uri" . }}
          - name: HORUSEC_JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
              {{- toYaml .Values.global.jwt.secretKeyRef | nindent 16 }}
          {{- if .Values.components.webhook.extraEnv }}
          # Extra environment variables
          {{- toYaml .Values.components.webhook.extraEnv | nindent 12 }}
          {{- end }}
          image: "{{ template "webhook.image" . }}"
          imagePullPolicy: {{ .Values.components.webhook.container.image.pullPolicy | quote }}
          name: horusec-webhook
          ports:
          {{- range $key, $value := .Values.components.webhook.port }}
            - containerPort: {{ $value }}
              name: {{ $key }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /webhook/health
              port: http
              scheme: HTTP
          {{- if .Values.components.webhook.container.livenessProbe }}
            failureThreshold: {{ .Values.components.webhook.container.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.components.webhook.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.components.webhook.container.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.components.webhook.container.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.components.webhook.container.livenessProbe.timeoutSeconds }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /webhook/health
              port: http
              scheme: HTTP
          {{- if .Values.components.webhook.container.readinessProbe }}
            failureThreshold: {{ .Values.components.webhook.container.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.components.webhook.container.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.components.webhook.container.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.components.webhook.container.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.components.webhook.container.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.components.messages.container.resources }}
          resources: {{- toYaml .Values.components.messages.container.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.components.webhook.container.securityContext.enabled }}
          securityContext: {{- omit .Values.components.webhook.container.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
      {{- if .Values.components.webhook.pod.securityContext.enabled }}
      securityContext: {{- omit .Values.components.webhook.pod.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: webhook
      terminationGracePeriodSeconds: 30
