apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-v1-2-v2"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-v1-2-v2-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-v1-2-v2"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-v1-2-v2-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: horusec-api-v1-2-v2
        image: "horuszup/horusec-api:2.11.0-rc"
        command: "./horusec-api-v1-to-v2-migrate"
        env:          
          - name: MIGRATION_NAME
            value: "platform"
        {{- range .Values.env }}
          - name: {{ .name }}
            value: "{{ .value }}" 
        {{- end }}
        {{- range .Values.envFromSecret }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .key }}
                key: {{ .key }}
        {{- end }}
